services:
  - type: web
    name: trace-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: EXASOL_HOST
        sync: false
      - key: EXASOL_USER
        sync: false
      - key: EXASOL_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false